### ISSUE TITLE
Player is never logged out after being AFK for a while.

### ISSUE THREAD

**Issue by wowadict** [mangosvb/serverZero#10]
When a player goes AFK and stays that way for a long period of time, they never timeout and get disconnected like they should.

**Comment by jaxx56** [comment]
Do not know if this was ever "fixed" in a comment or not, but as it stands the player will DC to the Character Screen after awhile and then disconnect to the Login Screen if the player does not log in.

**Comment by jaxx56** [comment]
It kicks me when i go afk for a long time in game.
