### ISSUE TITLE
Unknown OpCode in ClusterServer [CMSG_LOGOUT_CANCEL] 

### ISSUE THREAD

**Issue by Kaev** [mangosvb/serverZero#109]
[12:44:36] [127.0.0.1:51454] Unknown Opcode 0x0000004E [CMSG_LOGOUT_CANCEL], Dat
aLen=4
[12:44:36] [127.0.0.1:51454] DEBUG: Packet Dump - Length=6
|  00 04 4E 00 00 00                               |   ♦N              |

**Comment by jaxx56** [comment]
Upon investigation, this OpCode is not handled anywhere in the Cluster.. It's handled exclusively in the WorldServer.

Perhaps this should also be handled via cluster.

**Comment by Meltie2013** [comment]
This was implemented in commit: https://github.com/mangosvb/serverZero/commit/5ae6e8fd8265df6d9ea56c8f6a138ed8bd6132aa
