### ISSUE TITLE
Visual Studio is build uppercase .dll

### ISSUE THREAD

**Issue by Ituury** [mangosvb/serverZero#123]
**Description:**

Visual Studio is building the all the .dll files in an uppercase notation e.g Scripts.dll and Shared.dll

**Current behaviour:**

> Failed to find shared.dll, server startup aborted

**Expected behaviour:**

The server should start normal without the error

**Steps to reproduce the problem:**

1. Step 1 Build the project in visual studio
2. Step 2 Start the RealmServer.dll
3. Step 3 Failed to find shared.dll, server startup aborted

**Solution**

Change the if condtion in the files to an uppercase notation.

**Operating system:**

Windows 10 | 1803 x64

**Comment by Meltie2013** [comment]
Shared.dll should be with the compiled files. Make sure all dlls are in the folder you have the executables at. Never seen this issue when the change happened.

Best to double check to make sure all required files are being compiled,

**Comment by Ituury** [comment]
The executables are in the same directory. And the fix work if i change the if statement. I'm using VS2017.

**Comment by Meltie2013** [comment]
Going to fix the issue here in the next upcoming commit. @billy1arm Forgot to put them in upper case.

**Comment by billy1arm** [comment]
@Meltie2013 - I matched the case of your previous commit
