### ISSUE TITLE
DBC Extractor Framework Version Mismatch

### ISSUE THREAD

**Issue by Meltie2013** [mangosvb/serverZero#126]
**Description:**

Framework mismatch when running DBC Extractor. Calling Framework Version 2 instead of installed versions on the system. Other issues may accompany this as well.

**Current behaviour:**

```
Unhandled Exception: System.TypeInitializationException: The type initializer for
'DBCExtractor.MainModule' threw an exception. ---> 
System.IO.FileLoadException: Mixed mode assembly is built against version 'v2.0.50727' of the 
runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
   at DBCExtractor.MainModule..cctor()
   --- End of inner exception stack trace ---
   at DBCExtractor.MainModule.Main()
```

**Steps to reproduce the problem:**

1. Compile tools
2. Run DBC Extractor in our World of Warcraft Folder
3. ???

**Operating system:**

Windows 10

**Additional Information**
`Framework Version 4.6.1`
Seems to be calling Framework Version 2.0.x with the main assembly and possibly needs to be updated to Framework Version 3.5 or later.

@Krilliac @billy1arm

**Comment by Flaires** [comment]
I have not problems with the DBC Extractor. I had the same issue but i added in my PR the following line in the **app.config**: 
`<startup useLegacyV2RuntimeActivationPolicy="true" >`

The Extractor starts without any problems. It's just a temporary fix.

**Comment by Meltie2013** [comment]
I tested with it false and true and got the same result. This more then likely a library issue.
What version of windows do you have?

**Comment by Flaires** [comment]
I have Windows 10 x64 V 1803

Thats strange my Extractor works.
![tempsnip](https://user-images.githubusercontent.com/27811860/39750199-e6906b4a-52b4-11e8-8bca-f6c76aa8ae85.png)

**Comment by Meltie2013** [comment]
Try using it on the game client. It does work fine in the bin folder, but the error comes from extracting the data though.

**Comment by Flaires** [comment]
@Meltie2013 I will try it later this day. Thanks for the info.

**Comment by Meltie2013** [comment]
No, I build in x86; same as the servers. The problem I think is, the Extractor is still calling Framework v2 and causing the mismatch error. Only Framework I have installed is v.4.6.1.

I believe we need to update the Framework for the Extractor to v3.5 or later.

Compile Output
![image](https://user-images.githubusercontent.com/5354732/39793447-299beac6-530b-11e8-923a-5cf7bf258ea3.png)
With Debug
![image](https://user-images.githubusercontent.com/5354732/39793528-7b442c4e-530b-11e8-965a-64023d2ca57a.png)

With Release
![image](https://user-images.githubusercontent.com/5354732/39793412-03516cf6-530b-11e8-923c-759ce049e0b6.png)

**Comment by Flaires** [comment]
@Meltie2013 Okay i see. But I guess that the MpqLib needs an newer version of .Net, so the Extrector can load it. The Extrector is build with 4.0 in my case. It's just a guess, perhaps you can confirm it.

**Comment by Meltie2013** [comment]
Not sure if we have the original source code for MpqLib, since we picked up this project from the original owner that developed this.

Might have to code in the left overs to get it working under a different Framework version. I don't know much about the extractors myself, mainly a coder in the server stuff. I will see what I can do.

**Comment by Flaires** [comment]
I will look also for the sources.

And i think it's clear now, why it isn't working.
![capture](https://user-images.githubusercontent.com/27811860/39800185-48033e36-5367-11e8-8cb3-0971bac41170.PNG)

**Comment by Meltie2013** [comment]
Yeah, what I found as well. It works if you install Framework Version 2.0.x on your computer, but most users will make it an issue. That version is from the early 2000's, mostly 2005 according to wikipedia.

https://en.wikipedia.org/wiki/Template:.NET_Framework_version_history

**Comment by Flaires** [comment]
@billy1arm Would be awesome if you can publish the source it into an repo for this organisation. Thanks.

**Comment by Flaires** [comment]
@billy1arm Could you get it to work ? If not, please see my post above. I really want to help you guys.

**Comment by Meltie2013** [comment]
@Flaires Srry, we all been very busy with personal stuff. I am planning to start work on this project here soon. I hope to see you around again in the future.

**Comment by Flaires** [comment]
@Meltie2013 Cool great to hear, thanks for the update. In will try my best to support you!

**Comment by Flaires** [comment]
I want to look into this issue during the weekend. What possibilities do we have ? Update MpqLib to .Net 4 or is it possible to use the mangosZero extractor ? But I assume mangosVB handle the files different right ?  As mentioned, i can't obtain the source, because the original website is down unfortunately. And decompiling the .dll would be hard right ?  :D Are there any other possibilities ?

**Comment by Meltie2013** [comment]
Right now, I haven't heard anything about the MPQ Library from @billy1arm . I might have to write the library or port over the structure data from Mangos C++ (Vanilla) for the extractors. MangosVB has different extractor data with both DBC and Map Data.

**Comment by Flaires** [comment]
I hope I can support you, my skills in porting libraries are within limits, but I would love to give it a try.

**Comment by Flaires** [comment]
Any news here? At the moment I have some free time. @billy1arm could you please upload the library here or maybe create a separate repository for it? Many thanks.

**Comment by Romfos** [comment]
This issue is fixed as part of https://github.com/mangosvb/serverZero/pull/132

@billy1arm I think this issue should be closed

**Comment by billy1arm** [comment]
@Romfos  Thank you
