### ISSUE TITLE
Can I get the C # version? It's vb.net.

### ISSUE THREAD

**Issue by scc172fly** [mangosvb/serverZero#130]
Are there any plans to use c# in your development route?

**Comment by Meltie2013** [comment]
There is currently no c# version of this source. The only c# version available is one I started porting over a few years ago, which is not in a usable state.

This project kind of comes and goes depending on if we have enough time to work on it.

**Comment by billy1arm** [comment]
There is another project called Arctium https://github.com/Arctium
- Which is a C# project for wow

It has no affiliation with mangos at all though.
