### ISSUE TITLE
Migrate from VB to C#

### ISSUE THREAD

**Issue by Romfos** [mangosvb/serverZero#147]
Hi, 

I have a proposition to migrate current project from VB to C#

Why it could be useful:
1) C# is number 1 language in .NET world
2) C# community is bigger than VB. Most people know C#, but not VB
3) C# have better tooling and better support in IDE
4) Most examples\guides in internet are about C#, not VB. It will be easier for new contributors to find info about API\Interfaces e.t.c
5) VB don't support some latest features in .NET world and have strange support from Microsoft

Steps:
1. Freeze current repo
2. Create new MaNGOS.NET organization on github and MaNGOS.NET zero repo
3. Push current codebase to new repo (with all git histroy)
4. Step by step migrate project to C#

@billy1arm  @Krilliac @Meltie2013

**Comment by envis10n** [comment]
+1

**Comment by Meltie2013** [comment]
@Romfos You are right about going to C#. @Krilliac and I talked about this a few years back and just never got to that point yet. Lots to do to make that happen.

**Comment by billy1arm** [comment]
Hi, @Meltie2013 @Romfos @Krilliac - I have absolutely no issues moving to C#.

I spoke to @envis10n yesterday about this very thing since he had already made a start on this and set up a repository to support getting something even half ready before moving it to it's final 'home'.

For its final home, I would propose moving it into the main MangosZero repo as a separate project. If we can get them both to use the same databases, it kind of makes sense.

Doing this also gives us a chance to make the C# mangos even more mainstream and noticed.

For now, I will add you to the private repo until we have a version that actually compiles and loads (it doesn't atm).

**Comment by Elmsroth** [comment]
Yeah +1

**Comment by Kaev** [comment]
+1, should swap to .NET Core aswell so the core runs on other e.g. Linux aswell. :)

**Comment by billy1arm** [comment]
> +1, should swap to .NET Core aswell so the core runs on other systems e.g. Linux aswell. :)

That's already been done

**Comment by devwar87** [comment]
Hello, I will share this here maybe it can be useful.

This is Common/Shared/Realm/Cluster/WorldServer projects on C#. Did not drop Microsoft.VisualBasic reference just yet but it compiles and it works. Can get in world, etc.

[MangosCSharp.zip](https://github.com/mangosvb/serverZero/files/5368433/MangosCSharp.zip)

**Comment by Krilliac** [comment]
@devwar87 
We just got a compiling & working version up on the private repo a few hours ago. But We'll take a took at that and see if there's anything that can be merged or picked. We, of course are also looking for more developer's that are interesting in joining the private repository & MaNGOS Dev discord.

**Comment by devwar87** [comment]
> @devwar87
> Thank you for the conversion, we just got a compiling & working version up on the private repo a few hours ago. But We'll take a took at that and see if there's anything that can be merged or picked. We, of course are also looking for more developer's that are interesting in joining the private repository & MaNGOS Dev discord.

Mind adding me to that repo?

**Comment by Krilliac** [comment]
@devwar87 Messaged @billy1arm

**Comment by billy1arm** [comment]
@devwar87 You should now have access, make sure you log into github and check for an invite (which should come through your email)
