### ISSUE TITLE
When using melee attacks.. It's actually being counted as Holy damage

### ISSUE THREAD

**Issue by billy1arm** [mangosvb/serverZero#63]
when using melee attacks.. It's not Physical damage. It's actually being counted as Holy damage (With at least 50% of it being resisted).. and since spells appear to be bugged with being fully resisted/missed a lot of the times.. this is where the problem is coming in at.

**Comment by Krilliac** [comment]
Fixed in 83386de5e513d49906ec3083bf346e061c1aa899
