### ISSUE TITLE
Player Bank

### ISSUE THREAD

**Issue by Meltie2013** [mangosvb/serverZero#68]
I noticed when you try to place in items in the Player Bank, the items either go gray or you lose them completely.  I believe SQL Query is not correct, or missing table data.

**Comment by Kaev** [comment]
Also this one https://github.com/mangosvb/serverZero/commit/8af5f8d973c3859181f46141b96d6939d8786a08

**Comment by Meltie2013** [comment]
This issue was moved to emu-dev/mangosvb#3
