### ISSUE TITLE
Error when entering areatrigger

### ISSUE THREAD

**Issue by jaxx56** [mangosvb/serverZero#79]
[09:28:23] Error when entering areatrigger.
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at mangosVB.WorldServer.WS_CharMovement.On_CMSG_AREATRIGGER(PacketClass& pack
et, ClientClass& client) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Ha
ndlers\WS.Handlers.CharMovement.vb:line 396

**Comment by Meltie2013** [comment]
This issue was moved to emu-dev/mangosvb#10
