### ISSUE TITLE
Unhandled Packet in WorldServer [CMSG_FORCE_MOVE_ROOT_ACK]

### ISSUE THREAD

**Issue by jaxx56** [mangosvb/serverZero#89]
CMSG_FORCE_MOVE_ROOT_ACK [Unhandled Packet]

**Comment by Kaev** [comment]
Seems like this packet isn't used by MaNGOS
https://github.com/mangoszero/server/blob/fd103ef7e7581d2573c17531d13ef074dfea1b2c/src/game/WorldHandlers/MiscHandler.cpp#L931

**Comment by jaxx56** [comment]
Might need to check other cores.. this could also be used for the root command and possibly the movement anticheat
