### ISSUE TITLE
AuctionHouse issues

### ISSUE THREAD

**Issue by jaxx56** [mangosvb/serverZero#92]
You can place items into the AH but it has a few issues.

May take a long time to search for items on the Auction.
Displays auction bids as 0 copper regardless of price placed.
Auctions may appear as a blank icon.
Unending "..." loading for the seller's name.
Can't buy Auctions.

http://prntscr.com/8bn26w
May appear when trying to click on the auction. 
This looks like a packet structure issue.

**Comment by Meltie2013** [comment]
This issue was moved to emu-dev/mangosvb#4

**Comment by Meltie2013** [comment]
This was fixed in commits:
https://github.com/emu-dev/mangosvb/commit/db9de91d2a5c0c69ffcfb7b43de84d42d3c2f48b
https://github.com/emu-dev/mangosvb/commit/e056712ce1b6a68c8c64bc56349fd38d60a01e7b
https://github.com/emu-dev/mangosvb/commit/c5b752c37b39ddd2cb57f2af607018bb2a0186fc
